#!/bin/bash

echo 'Hello World'

apt-get install -y \
    build-essential \
    git \
    cmake \
    libboost-all-dev \
    libopenmpi-dev \
    libeigen3-dev \
    libblas-dev \
    liblapack-dev \
    libsqlite3-dev \
    doxygen \
    python3 \
    python3-pip \
    python3-opencv \
    cppcheck \
    bc \
    ninja-build \
    rsync \
    python-is-python3 \
    graphviz \
    mesa-common-dev \
    mesa-utils \
    freeglut3-dev