#!/bin/bash

# git clone https://gitlab.kitware.com/paraview/paraview.git paraview_git
# mkdir paraview
# cd paraview_git
# git checkout v5.12.0
# git submodule update --init --recursive
# cd ../paraview
cmake -GNinja \
      -DPARAVIEW_USE_PYTHON=ON \
      -DPARAVIEW_USE_MPI=ON \
      -DPARAVIEW_BUILD_WITH_EXTERNAL=OFF \
      -DPARAVIEW_ENABLE_RAYTRACING=OFF \
      -DVTK_SMP_IMPLEMENTATION_TYPE=TBB \
      -DCMAKE_BUILD_TYPE=Release \
      ../paraview_git
ninja -j $nproc
